apiVersion: v1
kind: Service
metadata:
  namespace: mohneesh-9797
  name: falcon-aggregator
  labels:
    app: mohneesh-9797
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6055
  selector:
    name: falcon-aggregator
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: mohneesh-9797
  name: falcon-aggregator
  labels:
    app: mohneesh-9797
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: falcon-aggregator
    spec:
      containers:
        - name: falcon-aggregator
          image: registry.cn-hangzhou.aliyuncs.com/mohneesh-9797/aggregator:v0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6055
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /mohneesh-9797/aggregator/config
              name: falcon-aggregator-config
            - mountPath: /etc/localtime
              name: tz-config
      volumes:
        - flexVolume:
            driver: alicloud/nas
            options:
              path: /mohneesh-9797/falcon-aggregator/config
              server: xxx.cn-hangzhou.nas.aliyuncs.com
              vers: "4.0"
          name: falcon-aggregator-config
        - hostPath:
            path: /etc/localtime
            type: ''
          name: tz-config